name: tik_tok_live_dart
description: Tik-tok live client
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  path: ^1.8.0
  fixnum: ^1.0.1
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
